import type { InstrumentSpec } from "./types";

export const INSTRUMENTS: InstrumentSpec[] = [
  {
    symbol: "EUR/USD",
    name: "Euro / US Dollar",
    kind: "forex",
    baseCurrency: "EUR",
    quoteCurrency: "USD",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "GBP/USD",
    name: "British Pound / US Dollar",
    kind: "forex",
    baseCurrency: "GBP",
    quoteCurrency: "USD",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "USD/JPY",
    name: "US Dollar / Japanese Yen",
    kind: "forex",
    baseCurrency: "USD",
    quoteCurrency: "JPY",
    pricePrecision: 3,
    pipPrecision: 2,
    pipSize: 0.01,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "USD/CHF",
    name: "US Dollar / Swiss Franc",
    kind: "forex",
    baseCurrency: "USD",
    quoteCurrency: "CHF",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "AUD/USD",
    name: "Australian Dollar / US Dollar",
    kind: "forex",
    baseCurrency: "AUD",
    quoteCurrency: "USD",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "USD/CAD",
    name: "US Dollar / Canadian Dollar",
    kind: "forex",
    baseCurrency: "USD",
    quoteCurrency: "CAD",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "EUR/GBP",
    name: "Euro / British Pound",
    kind: "forex",
    baseCurrency: "EUR",
    quoteCurrency: "GBP",
    pricePrecision: 5,
    pipPrecision: 4,
    pipSize: 0.0001,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "GBP/JPY",
    name: "British Pound / Japanese Yen",
    kind: "forex",
    baseCurrency: "GBP",
    quoteCurrency: "JPY",
    pricePrecision: 3,
    pipPrecision: 2,
    pipSize: 0.01,
    contractSize: 100000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "XAU/USD",
    name: "Gold / US Dollar",
    kind: "metal",
    baseCurrency: "XAU",
    quoteCurrency: "USD",
    pricePrecision: 2,
    pipPrecision: 1,
    pipSize: 0.1,
    contractSize: 100,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "XAG/USD",
    name: "Silver / US Dollar",
    kind: "metal",
    baseCurrency: "XAG",
    quoteCurrency: "USD",
    pricePrecision: 3,
    pipPrecision: 2,
    pipSize: 0.01,
    contractSize: 5000,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "BTC/USD",
    name: "Bitcoin / US Dollar",
    kind: "crypto",
    baseCurrency: "BTC",
    quoteCurrency: "USD",
    pricePrecision: 2,
    pipPrecision: 2,
    pipSize: 0.01,
    contractSize: 1,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "ETH/USD",
    name: "Ethereum / US Dollar",
    kind: "crypto",
    baseCurrency: "ETH",
    quoteCurrency: "USD",
    pricePrecision: 2,
    pipPrecision: 2,
    pipSize: 0.01,
    contractSize: 1,
    minLot: 0.01,
    lotStep: 0.01,
  },
  {
    symbol: "US30/USD",
    name: "Wall Street 30",
    kind: "index",
    baseCurrency: "US30",
    quoteCurrency: "USD",
    pricePrecision: 1,
    pipPrecision: 1,
    pipSize: 1,
    contractSize: 1,
    minLot: 1,
    lotStep: 1,
  },
  {
    symbol: "US100/USD",
    name: "Nasdaq 100",
    kind: "index",
    baseCurrency: "US100",
    quoteCurrency: "USD",
    pricePrecision: 1,
    pipPrecision: 1,
    pipSize: 1,
    contractSize: 1,
    minLot: 1,
    lotStep: 1,
  },
  {
    symbol: "SPX/USD",
    name: "S&P 500",
    kind: "index",
    baseCurrency: "SPX",
    quoteCurrency: "USD",
    pricePrecision: 1,
    pipPrecision: 1,
    pipSize: 1,
    contractSize: 1,
    minLot: 1,
    lotStep: 1,
  },
];

const instrumentBySymbol = new Map(INSTRUMENTS.map((instrument) => [instrument.symbol, instrument]));

export function listSupportedInstruments(): InstrumentSpec[] {
  return INSTRUMENTS;
}

export function findInstrument(symbol: string): InstrumentSpec | undefined {
  return instrumentBySymbol.get(symbol.toUpperCase());
}
